pipeline {
    agent any

    stages {

        stage('Build Docker Image') {
            steps {
                bat 'cd backend && docker compose build'
            }
        }

        stage('Run Docker Container') {
            steps {
                bat 'cd backend && docker compose up -d'
            }
        }

        stage('Check Running Containers') {
            steps {
                bat 'docker ps'
            }
        }
    }
}